:toc:

# Searchusc

This project UI was generated with [Angular CLI](https://github.com/angular/angular-cli) version 11.1.2.

The server (in `fastapi/`) is in Python, using the FastAPI framework.

## User interface: Angular 11

### Development server

Run `ng serve` for a dev server. Navigate to `http://localhost:4200/`. The app will automatically reload if you change any of the source files.

### Code scaffolding

Run `ng generate component component-name` to generate a new component. You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module`.

### Build

Run `ng build` to build the project. The build artifacts will be stored in the `dist/` directory. Use the `--prod` flag for a production build.

### Running unit tests

Run `ng test` to execute the unit tests via [Karma](https://karma-runner.github.io).

### Running end-to-end tests

Run `ng e2e` to execute the end-to-end tests via [Protractor](http://www.protractortest.org/).

### Further help

To get more help on the Angular CLI use `ng help` or go check out the [Angular CLI Overview and Command Reference](https://angular.io/cli) page.

## Server: FastAPI

The server is built with FastAPI. It is self documenting (see `http://localhost:8000/docs`) and has a simple interface to translate server queries into elasticsearch queries.

### Quickstart

1. Install Python (>= v3.7) and Python virtual environment (I prefer `pyenv virtualenvironments`).

```bash
$ pyenv virtualenv 3.7.4 searchusc
```

+
2. Install requirements from `requirements.txt` (or from `dev.txt` to add development features like iPython):

```bash
$ pyenv activate searchusc
(searchusc)$ cd requirements_py
(searchusc)$ pip install -r requirements.txt
```

+
3. Run server

```bash
$ pyenv activate searchusc
(searchusc)$ cd fastapi
(searchusc)$ uvicorn main:app --reload
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [43920] using statreload
INFO:     Started server process [43931]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

Navigate to `http://localhost:8000/docs` to confirm that the API is working


Serve the API through a proxy on the same port as the Angular application at `/service_py/`, e.g. `/service_py/search?q=Conservation`.
